// Loaded fact table - references a shared expression
table fact-sales
	lineageTag: 00000002-0000-0000-0000-000000000001

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: 00000003-0000-0000-0000-000000000001
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 00000003-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 00000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

	column ship_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 00000003-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: ship_date

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 00000003-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	measure '_Row Count Helper' = COUNTROWS('fact-sales')
		isHidden
		lineageTag: 00000003-0000-0000-0000-000000000099
		formatString: #,##0

	measure 'Order Fulfillment Summary' = [Open Order Count] & " open, status: " & SELECTEDVALUE('helper-order-lookup'[status_code])
		lineageTag: 00000003-0000-0000-0000-000000000098
		formatString: 0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact-sales = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = #"source-dataflow-standard",
				    #"Removed Columns" = Table.RemoveColumns(Source, {"internal_flag"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Exception
